Style updates
timber/docs pull request #23
Opened 2020-09-02 13:13 UTC by johnkeough

2020-09-17 14:28 UTC, gchtr commented
Hey @johnkeough 

I see you’re still working on the styles. I only have a heads up: It would be great if you could exclude all the files that are built automatically from your pull requests, like all the files in the **build** or **docs** folder. It’s easier to look at the changes without these files.

Tell me if you need help doing that.

Looking forward to see your work! :)

2020-09-17 15:06 UTC, johnkeough commented
Hey @gchtr !

Absolutely. I haven't before though, would you mind giving me a few pointers on how to do that?

Thank you! :)

2020-09-17 15:10 UTC, gchtr commented
Okay, let’s see. What do you use to manage Git? An app like Sourcetree, Fork or GitHub Desktop or do you use Git with the CLI?

2020-09-17 15:14 UTC, johnkeough commented
I use Git with the CLI for mostly all, no external apps.

2020-09-21 20:42 UTC, stephalee commented on assets/sass/_headings.scss
> +        // background: linear-gradient(to right, $green-light, rgba(0, 0, 0, 0) 75%);
delete commented out code

2020-09-21 20:42 UTC, stephalee commented on assets/sass/_headings.scss
> +    // font-size: 0.875rem;
delete commented out code

2020-09-21 20:43 UTC, stephalee commented on assets/sass/_sidebar.scss
> +		// padding: 0 0.5em;
commented out code

2020-09-21 20:43 UTC, stephalee commented on assets/sass/_toc.scss
> +	// border-bottom: 1px solid $border-color;
commented out code

2020-09-21 20:43 UTC, stephalee commented on assets/sass/_toc.scss
> +		border-bottom: 1px solid #323436;
can we use a color var here?

2020-09-21 20:46 UTC, stephalee reviewed
Looking good @johnkeough! In general, I'd try to remove all commented out styles before merging, I work this way when trying out new colors too (: but once you feel good about the changes you'd made I'd just make sure all of those are removed. I commented on a few of them but didn't want to be repetitive. Still looking into what the best way to exclude the `docs` and `build` folder files is

2020-09-22 05:22 UTC, gchtr commented
I think you can do

```
git checkout origin/master -- ./docs && git checkout origin/master -- ./content
```

to revert the changes to the built files (according to [this Stack Overflow answer](https://stackoverflow.com/a/44355701/1059980)). 

Also, did you make sure that you checked out the [`2.x`](https://github.com/timber/timber/tree/2.x) branch in the Timber repository that lies next to the docs repository? I realized there are some old file headers in the **content** folder. Sorry about that, I guess I didn’t document that in the Readme, because the docs are still in a transition state until the `2.x` branch is merged.

2020-09-27 18:00 UTC, gchtr requested changes
Wow, that looks great! I’ve always been in love with the GT America font. And I love what you did with the syntax higlighted parts! I’ve yet to get used to all the dark modes and interfaces. I saw that it’s based on the new [Upstatement](https://www.upstatement.com/) design. Nice!

I only have a couple of points where I think we have to find a compromise between design decisions and the reality that docs are a daily tool for developers that needs to readable and easy to navigate.

I saw that you only added light font styles. I guess now all strong text is rendered with a faux bold style, which is generated by the browser. Do you have a bold or even an extra bold font that you could add? I know, it’s a design decision to not use bold. But in the Timber documentation, we kinda use the convention to use `<strong>` to mark file names and file paths.

To me, the problem can also be seen in the navigation. Here, I think it’s too hard to see on which page I currently am:

![grafik](https://user-images.githubusercontent.com/2084481/94370014-7aa7d280-00ed-11eb-9458-a870d5bc131b.png)

Currently, there’s no way to see where there’s a link. Take this example:

![grafik](https://user-images.githubusercontent.com/2084481/94369967-21d83a00-00ed-11eb-8d15-2351f5cae81c.png)

There are actually two links in here:

![grafik](https://user-images.githubusercontent.com/2084481/94369978-3a485480-00ed-11eb-97ce-aae9d3cc8a0a.png)

It’s important to not only style text links, but also `<code>` elements that are links.

I realized it might not even be enough to style links with color only, as it’s done in the [current documentation](https://timber.github.io/docs/v2). We should probably add underlines to links in content, because we already use colored text a lot in the content when using `<code>` elements. That would also be better for acessibility, especially for people with a form of color blindness.

It’s a different thing with navigations or the table of contents, which consist mostly only of links. But then there are elements like tables with an overview over object properties and methods, where sometimes there are links, and sometimes there aren’t.

![grafik](https://user-images.githubusercontent.com/2084481/94372057-125fed80-00fb-11eb-809e-6a77f1197ebd.png)

It would be great if you could improve on these points :).

2020-09-30 00:31 UTC, jarednova commented
@gchtr thanks for the helpful feedback as always. @johnkeough got called away this week for another project, but when he returns I'll help him address these points in the next go!

2020-10-09 00:58 UTC, jarednova commented
@johnkeough let's talk next week about a solution to the font issue. We can serve [crossdomain fonts](https://davidwalsh.name/cdn-fonts) from upstatement.com, but I'm not sure it's worth the effort. FWIW I think it looks glorious in Helvetica.

2020-11-05 21:20 UTC, johnkeough commented
Thank you for the great feedback @gchtr ! 

Here are the updated changes @jarednova :
- Removing GT America and using default Helvetica
- On the sidebar nav, adding an underline to your current page
![image](https://user-images.githubusercontent.com/42050088/98297169-00872b00-1f82-11eb-8676-dd2c252fdbb6.png)

- Globally change text and code link styling to include a green underline
![image](https://user-images.githubusercontent.com/42050088/98297285-2ca2ac00-1f82-11eb-8dc7-75e6d959e5ef.png)
![image](https://user-images.githubusercontent.com/42050088/98297345-45ab5d00-1f82-11eb-9139-6e0833d75ca8.png)
![image](https://user-images.githubusercontent.com/42050088/98297405-58be2d00-1f82-11eb-8d5d-625bbb51fcef.png)

2020-11-13 16:29 UTC, jarednova commented
Looking much closer! I think everything you flagged in the last pass @gchtr has been taken care of. There's one more area I'd like to spend a little more time. These tables with the method/property type and definitions:
<img width="657" alt="Screen Shot 2020-11-13 at 11 25 55 AM" src="https://user-images.githubusercontent.com/1298086/99095636-6471ab00-25a3-11eb-98f8-a66c31e69dc0.png">

I was looking to apply some surrounding spans for `<span class="property">$language</span>` so that these can be style separately from the regular text. @gchtr does that markup/control reside within this repo? or in Teak?

2020-11-14 11:11 UTC, gchtr approved these changes
This is looking good now! I have only some changes in https://github.com/timber/docs/pull/30, but then this is good to go.

@jarednova I added some spans and classes to the Teak markup in the [1.0.3 release](https://github.com/timber/teak/compare/1.0.2...1.0.3). You can get it with `composer update timber/teak` in the docs repo. Will that work?

2020-11-19 02:46 UTC, jarednova commented
@gchtr I think so! I applied a few last color/style tweaks. The last fix depends on a PR I just submitted to Teak here:

https://github.com/timber/teak/pull/1

... this will allow proper lines breaks in the MD files which trigger the correct markup from 11ty. Could you give this one last look before we merge? I want to make sure the changes I made in 1d703baf57396b8433d5da454599be25d95648e4 work (I needed to include `typeface-source-sans-pro` in order to run/build — was this correct?)

2020-11-19 17:34 UTC, gchtr commented
> The last fix depends on a PR I just submitted to Teak here:
> 
> [timber/teak#1](https://github.com/timber/teak/pull/1)
> 
> ... this will allow proper lines breaks in the MD files which trigger the correct markup from 11ty.

Should be fixed now.

> Could you give this one last look before we merge?

I had a look and to me, all is fine now 👍

> I needed to include `typeface-source-sans-pro` in order to run/build — was this correct?)

I forgot to remove an entry in **webpack.mix.js**, that’s why that error appeared. Fixed in [`cbb056a` (#23)](https://github.com/timber/docs/pull/23/commits/cbb056af8e7dbe7d2aca9ea7c4ff0c20396b599f).

@jarednova I think you can go ahead and merge this.

2020-11-19 17:49 UTC, jarednova commented
¡¡¡¡MOST EXCELLENT!!!!

2020-11-19 17:49 UTC, merged